"""add_goals_revisions_tables

Revision ID: 1116be57a143
Revises: 2e41672ec080
Create Date: 2026-09-11 10:36:39.262442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1116be57a143'
down_revision: Union[str, None] = '2e41672ec080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration: create tables, add columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False, comment="Short goal title, e.g. 'EPAM SDE Placement'"),
    sa.Column('description', sa.Text(), nullable=True, comment='More detail about the goal and success criteria'),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True, comment='Deadline for this goal'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False, comment='Date when revision is scheduled'),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=True, comment='How long the revision took (self-reported)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='What the user reviewed or struggled with'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revisions_planned_date'), 'revisions', ['planned_date'], unique=False)
    op.create_index(op.f('ix_revisions_topic_id'), 'revisions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_revisions_user_id'), 'revisions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration: drop tables, remove columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revisions_user_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_topic_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_planned_date'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
