"""initial_schema

Revision ID: 2e41672ec080
Revises: 
Create Date: 2026-08-31 22:23:08.260413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e41672ec080'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration: create tables, add columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Subject name, e.g. 'Operating Systems'"),
    sa.Column('short_code', sa.String(length=20), nullable=True, comment="Short identifier, e.g. 'OS', 'DBMS', 'CN', 'DSA'"),
    sa.Column('description', sa.Text(), nullable=True, comment='What this subject covers'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's login email. Must be unique."),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Display name'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='bcrypt hash. Never store plaintext passwords.'),
    sa.Column('target_role', sa.String(length=100), nullable=True, comment="E.g. 'Software Engineer', 'Data Scientist'"),
    sa.Column('target_companies', sa.String(length=500), nullable=True, comment='Comma-separated list or JSON string of target companies'),
    sa.Column('graduation_year', sa.Integer(), nullable=True, comment='Expected graduation year'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False for soft-deleted or banned accounts'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last modification timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False, comment='Which subject this topic belongs to'),
    sa.Column('name', sa.String(length=200), nullable=False, comment="Topic name, e.g. 'CPU Scheduling'"),
    sa.Column('description', sa.Text(), nullable=True, comment='What this topic covers and why it matters'),
    sa.Column('order_index', sa.SmallInteger(), nullable=False, comment='Display/learning order within the subject (0-indexed)'),
    sa.Column('difficulty', sa.String(length=10), nullable=False, comment='General difficulty: EASY, MEDIUM, HARD'),
    sa.Column('striver_link', sa.Text(), nullable=True, comment="Link to Striver's guide for this topic"),
    sa.Column('neetcode_link', sa.Text(), nullable=True, comment='Link to NeetCode roadmap entry'),
    sa.Column('is_gate_relevant', sa.Boolean(), server_default='false', nullable=False, comment='Is this topic commonly tested in GATE exams?'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Which user is tracking this problem'),
    sa.Column('topic_id', sa.Integer(), nullable=True, comment='DSA topic this problem belongs to (nullable — user may not categorize)'),
    sa.Column('title', sa.String(length=300), nullable=False, comment="Problem title, e.g. 'Trapping Rain Water'"),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='Source platform: LEETCODE, CODEFORCES, etc.'),
    sa.Column('platform_id', sa.String(length=50), nullable=True, comment="Platform-specific ID (e.g., LeetCode problem number '42')"),
    sa.Column('url', sa.Text(), nullable=True, comment='Direct URL to the problem'),
    sa.Column('difficulty', sa.String(length=10), nullable=False, comment='EASY, MEDIUM, or HARD'),
    sa.Column('tags', sa.Text(), nullable=True, comment='Comma-separated topic tags from the platform'),
    sa.Column('status', sa.String(length=15), nullable=False, comment='Current state in the solve lifecycle'),
    sa.Column('confidence', sa.String(length=10), nullable=False, comment="User's self-assessed confidence level"),
    sa.Column('revision_count', sa.SmallInteger(), nullable=False, comment='Number of times the user has deliberately revised this problem'),
    sa.Column('last_solved_date', sa.Date(), nullable=True, comment='When the user last solved/attempted this problem'),
    sa.Column('last_revised_date', sa.Date(), nullable=True, comment='When the user last went back to revise this problem'),
    sa.Column('notes', sa.Text(), nullable=True, comment="User's personal notes: approach, key insights, gotchas"),
    sa.Column('solution_approach', sa.Text(), nullable=True, comment='High-level description of the approach/algorithm used'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = soft deleted. Preserves attempt history.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_title'), 'problems', ['title'], unique=False)
    op.create_index(op.f('ix_problems_topic_id'), 'problems', ['topic_id'], unique=False)
    op.create_index(op.f('ix_problems_user_id'), 'problems', ['user_id'], unique=False)
    op.create_table('problem_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False, comment='Which problem was attempted'),
    sa.Column('result', sa.String(length=30), nullable=False, comment='Outcome of this attempt'),
    sa.Column('time_taken_minutes', sa.SmallInteger(), nullable=True, comment='How many minutes it took to attempt (self-reported)'),
    sa.Column('notes', sa.Text(), nullable=True, comment="What approach was tried, what didn't work, key learnings"),
    sa.Column('is_timed', sa.Boolean(), nullable=False, comment='Was this a timed/mock interview attempt?'),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this attempt occurred'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_attempts_attempted_at'), 'problem_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_problem_attempts_problem_id'), 'problem_attempts', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration: drop tables, remove columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_attempts_problem_id'), table_name='problem_attempts')
    op.drop_index(op.f('ix_problem_attempts_attempted_at'), table_name='problem_attempts')
    op.drop_table('problem_attempts')
    op.drop_index(op.f('ix_problems_user_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_topic_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_title'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
