"""add_study_plans_and_tasks

Revision ID: 467275009d2b
Revises: 1116be57a143
Create Date: 2026-09-12 16:54:33.078733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467275009d2b'
down_revision: Union[str, None] = '1116be57a143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration: create tables, add columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.SmallInteger(), nullable=False, comment='Total days the plan covers'),
    sa.Column('daily_hours', sa.Float(), nullable=False, comment='Target study hours per day'),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_goal_id'), 'study_plans', ['goal_id'], unique=False)
    op.create_index(op.f('ix_study_plans_user_id'), 'study_plans', ['user_id'], unique=False)
    op.create_table('study_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('day_number', sa.SmallInteger(), nullable=False, comment='Which day of the plan (1-indexed)'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.SmallInteger(), nullable=False, comment='Estimated time to complete in minutes'),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_tasks_plan_id'), 'study_tasks', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this migration: drop tables, remove columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_tasks_plan_id'), table_name='study_tasks')
    op.drop_table('study_tasks')
    op.drop_index(op.f('ix_study_plans_user_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_goal_id'), table_name='study_plans')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
